/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./common/components/ConfirmDialog.vue')['default']
    DefaultDialog: typeof import('./common/components/DefaultDialog.vue')['default']
    ExamConsole: typeof import('./modules/exam/components/ExamConsole.vue')['default']
    ExamCountDown: typeof import('./modules/exam/components/ExamCountDown.vue')['default']
    ExamEditor: typeof import('./modules/exam/components/ExamEditor.vue')['default']
    ExamResultView: typeof import('./modules/exam/views/ExamResultView.vue')['default']
    ExamSettingsView: typeof import('./modules/exam/views/ExamSettingsView.vue')['default']
    ExamView: typeof import('./modules/exam/views/ExamView.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInView: typeof import('./modules/auth/views/SignInView.vue')['default']
  }
}
