/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./common/components/CodeEditor.vue')['default']
    ConfirmDialog: typeof import('./common/components/ConfirmDialog.vue')['default']
    CountDown: typeof import('./common/components/CountDown.vue')['default']
    DefaultDialog: typeof import('./common/components/DefaultDialog.vue')['default']
    ExamResultView: typeof import('./views/ExamResultView.vue')['default']
    ExamSettingsView: typeof import('./views/ExamSettingsView.vue')['default']
    ExamView: typeof import('./views/ExamView.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInView: typeof import('./views/SignInView.vue')['default']
  }
}
